# Copyright (c) 2017 Intel Corporation. All rights reserved.
# Use of this source code is governed by a Apache License
# Version 2.0 license that can be found in the LICENSE file.
version: 2.1.{build}
branches:
  only:
  - development
skip_tags: true
environment:
  nodejs_version: "6"
image: Visual Studio 2015
clone_folder: c:\projects\librealsense
init:
- cmd: 
install:
- ps: Install-Product node $env:nodejs_version
- cmd: >-
    cd c:\projects\librealsense\.. && git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git 

    set OLDPATH=%PATH% && set PATH=%PATH%;c:\projects\depot_tools

    cd c:\projects\librealsense\wrappers\nodejs\tools && npm install

    cd c:\projects\librealsense\wrappers\nodejs && node .\tools\linter.js && set PATH=%OLDPATH% && set OLDPATH=
before_build:
- cmd: >-
    cd c:\projects\librealsense && mkdir build && cd build

    cmake .. -DBUILD_EXAMPLES=true -DBUILD_PYTHON_BINDINGS=true -DBUILD_NODEJS_BINDINGS:BOOL=true
build:
  project: ./build/librealsense2.sln
  verbosity: minimal
test_script:
- ps: >-
    $url_D435 = "http://realsense-hw-public.s3.amazonaws.com/rs-tests/D435_fw_5.8.9_lrs_2.8.0.x_Wed_10_18_17_15_53_15"

    $url_D415 = "http://realsense-hw-public.s3.amazonaws.com/rs-tests/D415_fw_5.8.9_lrs_2.8.0.x_Wed_10_18_17_15_53_15"

    $url_D405 = "http://realsense-hw-public.s3.amazonaws.com/rs-tests/D405_fw_5.8.9_lrs_2.8.0.x_Wed_10_18_17_15_53_15"

    $url_SR300 = "http://realsense-hw-public.s3.amazonaws.com/rs-tests/SR300_lrs_2.8.0.x_Wed_10_18_17_15_53_15"

    $output_D435 = "C:/projects/librealsense/build/Debug/live_test_D435"

    $output_D415 = "C:/projects/librealsense/build/Debug/live_test_D415"

    $output_D405 = "C:/projects/librealsense/build/Debug/live_test_D405"

    $output_SR300 = "C:/projects/librealsense/build/Debug/live_test_SR300"

    Invoke-WebRequest -Uri $url_D435 -OutFile $output_D435

    Invoke-WebRequest -Uri $url_D415 -OutFile $output_D415

    Invoke-WebRequest -Uri $url_D405 -OutFile $output_D405

    Invoke-WebRequest -Uri $url_SR300 -OutFile $output_SR300

    & cmd.exe /c C:/projects/librealsense/build/Debug/live-test.exe from C:/projects/librealsense/build/Debug/live_test_D435 -d yes

    if ($LASTEXITCODE -ne 0)
    {
        throw "D435 Tests failed!"
    }

    & cmd.exe /c C:/projects/librealsense/build/Debug/live-test.exe from C:/projects/librealsense/build/Debug/live_test_D415 -d yes

    if ($LASTEXITCODE -ne 0)
    {
        throw "D415 Tests failed!"
    }

    & cmd.exe /c C:/projects/librealsense/build/Debug/live-test.exe from C:/projects/librealsense/build/Debug/live_test_D405 -d yes

    if ($LASTEXITCODE -ne 0)
    {
        throw "D405 Tests failed!"
    }

    & cmd.exe /c C:/projects/librealsense/build/Debug/live-test.exe from C:/projects/librealsense/build/Debug/live_test_SR300 -d yes

    if ($LASTEXITCODE -ne 0)
    {
        throw "SR300 Tests failed!"
    }
    # TODO(halton): Add unit test for Node.js binding
